force-app/main/default/objects/JK_Employee__c/JK_Employee__c.object-meta.xml
<CustomObject>
    <description>Contains basic info about the employee</description>
    <label>JK_Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JK_Employee__c/fields/Emp_firstName__c.field-meta.xml
<CustomField>
    <fullName>Emp_firstName__c</fullName>
    <label>Emp_firstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_midName__c.field-meta.xml
<CustomField>
    <fullName>Emp_midName__c</fullName>
    <label>Emp_midName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/bulkenter.cls
public class bulkenter {
	public static void mains()
    {
        Integer i=1;
        for(Integer j=0;j<150;j++)
        {
        	String s ='prinson'+i;
        	JK_Employee__c ss = new JK_Employee__c(Emp_firstName__c =s , Emp_midName__c ='h');  
            i++;
            insert ss;
        }
    }
    public static void deletex()
    {
        List<JK_Employee__c> ss = [select Id from JK_Employee__c where Emp_midName__c ='h'];
        delete ss;
    }
}