force-app/main/default/objects/JK_Employee__c/JK_Employee__c.object-meta.xml
<CustomObject>
    <description>Contains basic info about the employee</description>
    <label>JK_Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JK_FamilyInfo__c/JK_FamilyInfo__c.object-meta.xml
<CustomObject>
    <label>JK_FamilyInfo</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>JK_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Familys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/EmpToFi__c.field-meta.xml
<CustomField>
    <fullName>EmpToFi__c</fullName>
    <label>EmpToFi</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_Familys</relationshipLabel>
    <relationshipName>JK_Familys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_dob__c.field-meta.xml
<CustomField>
    <fullName>Fi_dob__c</fullName>
    <label>Fi_dob</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_firstName__c.field-meta.xml
<CustomField>
    <fullName>Fi_firstName__c</fullName>
    <label>Fi_firstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_lastName__c.field-meta.xml
<CustomField>
    <fullName>Fi_lastName__c</fullName>
    <label>Fi_lastName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_middleName__c.field-meta.xml
<CustomField>
    <fullName>Fi_middleName__c</fullName>
    <label>Fi_middleName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_relation__c.field-meta.xml
<CustomField>
    <fullName>Fi_relation__c</fullName>
    <label>Fi_relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_WorkExperience__c/JK_WorkExperience__c.object-meta.xml
<CustomObject>
    <description>Gives the detial of employee work history beginning with the current employer to the oldest employer.</description>
    <label>JK_WorkExperience</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_WorkExperiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JK_WorkExperience__c/fields/WE_designationWhenLeaving__c.field-meta.xml
<CustomField>
    <fullName>WE_designationWhenLeaving__c</fullName>
    <label>WE_designationWhenLeaving</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_WorkExperience__c/fields/WE_from__c.field-meta.xml
<CustomField>
    <fullName>WE_from__c</fullName>
    <label>WE_from</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_WorkExperience__c/fields/WE_organizationName__c.field-meta.xml
<CustomField>
    <fullName>WE_organizationName__c</fullName>
    <label>WE_organizationName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_WorkExperience__c/fields/WE_reasonForLeaving__c.field-meta.xml
<CustomField>
    <fullName>WE_reasonForLeaving__c</fullName>
    <label>WE_reasonForLeaving</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/JK_WorkExperience__c/fields/WE_to__c.field-meta.xml
<CustomField>
    <fullName>WE_to__c</fullName>
    <label>WE_to</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_WorkExperience__c/fields/WeToEmp__c.field-meta.xml
<CustomField>
    <fullName>WeToEmp__c</fullName>
    <label>WeToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_WorkExperiences</relationshipLabel>
    <relationshipName>JK_WorkExperiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EO_PracController.cls
public with sharing class EO_PracController 
{
   
    //Wrapper Class
    public class EmployeeInfo
    {
        JK_Employee__c basicEmployeeInfo;
        List <JK_WorkExperience__c> employeeWorkExperience;
        List< JK_FamilyInfo__c> employeeFamilyInfo;
    }


    @RemoteAction
    public static EmployeeInfo employeeData()
    {
        String Id = 'a025h00000t9H7TAAU';
        EmployeeInfo e1 = new EmployeeInfo();
        e1.basicEmployeeInfo = [SELECT Id from JK_Employee__c WHERE Id = :Id];
        e1.employeeFamilyInfo = [SELECT CreatedById, CreatedDate, EmpToFi__c, Fi_dob__c, Fi_firstName__c, Fi_lastName__c, Fi_middleName__c, Fi_relation__c, Id, IsDeleted, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, Name, SystemModstamp FROM JK_FamilyInfo__c WHERE EmpToFi__c = :Id];
        e1.employeeWorkExperience = [SELECT Id, WE_organizationName__c, WE_designationWhenLeaving__c, WE_from__c, WE_to__c, WE_reasonForLeaving__c, WeToEmp__c FROM JK_WorkExperience__c  WHERE WeToEmp__c =: Id];
        //same or work and family
        return e1;
    }
}