force-app/main/default/objects/JK_Employee__c/JK_Employee__c.object-meta.xml
<CustomObject>
    <description>Contains basic info about the employee</description>
    <label>JK_Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_bloodGroup__c.field-meta.xml
<CustomField>
    <fullName>Emp_bloodGroup__c</fullName>
    <label>Emp_bloodGroup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A+ve</fullName>
            </value>
            <value>
                <fullName>A-ve</fullName>
            </value>
            <value>
                <fullName>B+ve</fullName>
            </value>
            <value>
                <fullName>B-ve</fullName>
            </value>
            <value>
                <fullName>AB+ve</fullName>
            </value>
            <value>
                <fullName>AB-ve</fullName>
            </value>
            <value>
                <fullName>O+ve</fullName>
            </value>
            <value>
                <fullName>O-ve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_commAddress__c.field-meta.xml
<CustomField>
    <fullName>Emp_commAddress__c</fullName>
    <label>Emp_commAddress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_commCity__c.field-meta.xml
<CustomField>
    <fullName>Emp_commCity__c</fullName>
    <label>Emp_commCity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_commonAddressCheck__c.field-meta.xml
<CustomField>
    <fullName>Emp_commonAddressCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_commonAddressCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_commState__c.field-meta.xml
<CustomField>
    <fullName>Emp_commState__c</fullName>
    <label>Emp_commState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_commZipCode__c.field-meta.xml
<CustomField>
    <fullName>Emp_commZipCode__c</fullName>
    <label>Emp_commZipCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_dateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>Emp_dateOfBirth__c</fullName>
    <label>Emp_dateOfBirth</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_emailId__c.field-meta.xml
<CustomField>
    <fullName>Emp_emailId__c</fullName>
    <label>Emp_emailId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_firstName__c.field-meta.xml
<CustomField>
    <fullName>Emp_firstName__c</fullName>
    <label>Emp_firstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_foodPref__c.field-meta.xml
<CustomField>
    <fullName>Emp_foodPref__c</fullName>
    <label>Emp_foodPref</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_gender__c.field-meta.xml
<CustomField>
    <fullName>Emp_gender__c</fullName>
    <label>Emp_gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1__c</fullName>
    <label>Emp_lang1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Speak</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2__c</fullName>
    <label>Emp_lang2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Speak</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3__c</fullName>
    <label>Emp_lang3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Read</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Speak</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lastName__c.field-meta.xml
<CustomField>
    <fullName>Emp_lastName__c</fullName>
    <label>Emp_lastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_maritalStatus__c.field-meta.xml
<CustomField>
    <fullName>Emp_maritalStatus__c</fullName>
    <label>Emp_maritalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Unmarried</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_midName__c.field-meta.xml
<CustomField>
    <fullName>Emp_midName__c</fullName>
    <label>Emp_midName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_mobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Emp_mobilePhone__c</fullName>
    <label>Emp_mobilePhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_nationality__c.field-meta.xml
<CustomField>
    <fullName>Emp_nationality__c</fullName>
    <label>Emp_nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>AMERICIAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resAddress__c.field-meta.xml
<CustomField>
    <fullName>Emp_resAddress__c</fullName>
    <label>Emp_resAddress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resCity__c.field-meta.xml
<CustomField>
    <fullName>Emp_resCity__c</fullName>
    <label>Emp_resCity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_resState__c.field-meta.xml
<CustomField>
    <fullName>Emp_resState__c</fullName>
    <label>Emp_resState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resZipCode__c.field-meta.xml
<CustomField>
    <fullName>Emp_resZipCode__c</fullName>
    <label>Emp_resZipCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_telephone__c.field-meta.xml
<CustomField>
    <fullName>Emp_telephone__c</fullName>
    <label>Emp_telephone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_tShirtSize__c.field-meta.xml
<CustomField>
    <fullName>Emp_tShirtSize__c</fullName>
    <label>Emp_tShirtSize</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/JK_FamilyInfo__c.object-meta.xml
<CustomObject>
    <label>JK_FamilyInfo</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>JK_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Familys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_firstName__c.field-meta.xml
<CustomField>
    <fullName>Fi_firstName__c</fullName>
    <label>Fi_firstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/JK_KycDetail__c.object-meta.xml
<CustomObject>
    <description>Contains the KYC Details of employees.</description>
    <label>JK_KycDetail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_KycDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentNumber__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentNumber__c</fullName>
    <label>Kyc_documentNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentType__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentType__c</fullName>
    <label>Kyc_documentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account (ICICI)</fullName>
            </value>
            <value>
                <fullName>Aadhar Card</fullName>
            </value>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>Voter Card</fullName>
            </value>
            <value>
                <fullName>ESIC Card</fullName>
            </value>
            <value>
                <fullName>Ration Card</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>UAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_nameOnDocument__c.field-meta.xml
<CustomField>
    <fullName>Kyc_nameOnDocument__c</fullName>
    <label>Kyc_nameOnDocument</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_remarks__c.field-meta.xml
<CustomField>
    <fullName>Kyc_remarks__c</fullName>
    <label>Kyc_remarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/KycToEmp__c.field-meta.xml
<CustomField>
    <fullName>KycToEmp__c</fullName>
    <label>KycToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_KycDetails</relationshipLabel>
    <relationshipName>KycToEmp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/pdfController.cls
public with sharing class pdfController
{
    //Wrapper Class
    public class EmployeeInfo
    {
        JK_Employee__c employeeInfo;
        List<JK_KycDetail__c> employeeKycInfo;
        List< JK_FamilyInfo__c> employeeFamilyInfo;
        List <JK_EducationalQualification__c> employeeEducationInfo;
        List <JK_WorkExperience__c> employeeWorkInfo;
    }

    @RemoteAction
    public static EmployeeInfo pdfData(String employeeId)
    {
        EmployeeInfo e1 = new EmployeeInfo();
        e1.employeeInfo = [SELECT Emp_firstName__c, Emp_midName__c, Emp_lastName__c, Emp_dateOfBirth__c, 
                            Emp_maritalStatus__c, Emp_gender__c, Emp_bloodGroup__c, Emp_nationality__c, 
                            Emp_emailId__c, Emp_telephone__c, Emp_mobilePhone__c, Emp_resAddress__c,
                            Emp_resCity__c, Emp_resState__c, Emp_resZipCode__c, Emp_commonAddressCheck__c, 
                            Emp_commAddress__c, Emp_commCity__c, Emp_commState__c, Emp_commZipcode__c, 
                            Emp_tShirtSize__c, Emp_foodPref__c, Emp_lang1__c, Emp_lang1Read__c, 
                            Emp_lang1Write__c, Emp_lang1Speak__c, Emp_lang2__c, Emp_lang2Read__c, 
                            Emp_lang2Write__c, Emp_lang2Speak__c, Emp_lang3__c, Emp_lang3Read__c, 
                            Emp_lang3Write__c, Emp_lang3Speak__c
                            FROM JK_Employee__c WHERE Id = :employeeId];

        e1.employeeKycInfo = [SELECT Id,Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,
                                Kyc_remarks__c FROM JK_KycDetail__c WHERE KycToEmp__c = :employeeId ];
        
        e1.employeeFamilyInfo = [SELECT Id,Fi_firstName__c , Fi_middleName__c , Fi_lastName__c , Fi_relation__c , Fi_dob__c  
                                    FROM JK_FamilyInfo__c WHERE EmpToFi__c =: employeeId];

        e1.employeeEducationInfo = [SELECT EQ_boardOrUniversity__c, EQ_branchTwelth__c, EQ_degree__c, 
                                    EQ_educationalLevel__c, EQ_marksType__c, EQ_percentageMarks__c, 
                                    EQ_postGradDegree__c, EQ_schoolOrCollegeName__c, EQ_specialisation__c, 
                                    EQ_yearOfPassing__c, EqToEmp__c, Id
                                    FROM JK_EducationalQualification__c WHERE EqToEmp__c=:employeeId ORDER BY EQ_yearOfPassing__c ASC];

        e1.employeeWorkInfo = [SELECT Id, WE_organizationName__c, WE_designationWhenLeaving__c, WE_from__c, 
                                WE_to__c, WE_reasonForLeaving__c, WeToEmp__c 
                                FROM JK_WorkExperience__c WHERE WeToEmp__c =: employeeID];
        return e1;
    }
}