force-app/main/default/objects/JK_Employee__c/JK_Employee__c.object-meta.xml
<CustomObject>
    <description>Contains basic info about the employee</description>
    <label>JK_Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_bloodGroup__c.field-meta.xml
<CustomField>
    <fullName>Emp_bloodGroup__c</fullName>
    <label>Emp_bloodGroup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A+ve</fullName>
            </value>
            <value>
                <fullName>A-ve</fullName>
            </value>
            <value>
                <fullName>B+ve</fullName>
            </value>
            <value>
                <fullName>B-ve</fullName>
            </value>
            <value>
                <fullName>AB+ve</fullName>
            </value>
            <value>
                <fullName>AB-ve</fullName>
            </value>
            <value>
                <fullName>O+ve</fullName>
            </value>
            <value>
                <fullName>O-ve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_commAddress__c.field-meta.xml
<CustomField>
    <fullName>Emp_commAddress__c</fullName>
    <label>Emp_commAddress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_commCity__c.field-meta.xml
<CustomField>
    <fullName>Emp_commCity__c</fullName>
    <label>Emp_commCity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_commonAddressCheck__c.field-meta.xml
<CustomField>
    <fullName>Emp_commonAddressCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_commonAddressCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_commState__c.field-meta.xml
<CustomField>
    <fullName>Emp_commState__c</fullName>
    <label>Emp_commState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_dateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>Emp_dateOfBirth__c</fullName>
    <label>Emp_dateOfBirth</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_emailId__c.field-meta.xml
<CustomField>
    <fullName>Emp_emailId__c</fullName>
    <label>Emp_emailId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_firstName__c.field-meta.xml
<CustomField>
    <fullName>Emp_firstName__c</fullName>
    <label>Emp_firstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_foodPref__c.field-meta.xml
<CustomField>
    <fullName>Emp_foodPref__c</fullName>
    <label>Emp_foodPref</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_gender__c.field-meta.xml
<CustomField>
    <fullName>Emp_gender__c</fullName>
    <label>Emp_gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1__c</fullName>
    <label>Emp_lang1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Speak</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang1Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang1Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang1Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2__c</fullName>
    <label>Emp_lang2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Speak</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang2Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang2Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang2Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3__c</fullName>
    <label>Emp_lang3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Read__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Read</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Speak__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Speak__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Speak</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lang3Write__c.field-meta.xml
<CustomField>
    <fullName>Emp_lang3Write__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emp_lang3Write</label>
    <type>Checkbox</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lastName__c.field-meta.xml
<CustomField>
    <fullName>Emp_lastName__c</fullName>
    <label>Emp_lastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_maritalStatus__c.field-meta.xml
<CustomField>
    <fullName>Emp_maritalStatus__c</fullName>
    <label>Emp_maritalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Unmarried</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_midName__c.field-meta.xml
<CustomField>
    <fullName>Emp_midName__c</fullName>
    <label>Emp_midName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_mobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Emp_mobilePhone__c</fullName>
    <label>Emp_mobilePhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_nationality__c.field-meta.xml
<CustomField>
    <fullName>Emp_nationality__c</fullName>
    <label>Emp_nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>AMERICIAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resAddress__c.field-meta.xml
<CustomField>
    <fullName>Emp_resAddress__c</fullName>
    <label>Emp_resAddress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resCity__c.field-meta.xml
<CustomField>
    <fullName>Emp_resCity__c</fullName>
    <label>Emp_resCity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_resState__c.field-meta.xml
<CustomField>
    <fullName>Emp_resState__c</fullName>
    <label>Emp_resState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resZipCode__c.field-meta.xml
<CustomField>
    <fullName>Emp_resZipCode__c</fullName>
    <label>Emp_resZipCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_telephone__c.field-meta.xml
<CustomField>
    <fullName>Emp_telephone__c</fullName>
    <label>Emp_telephone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_tShirtSize__c.field-meta.xml
<CustomField>
    <fullName>Emp_tShirtSize__c</fullName>
    <label>Emp_tShirtSize</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/JK_KycDetail__c.object-meta.xml
<CustomObject>
    <description>Contains the KYC Details of employees.</description>
    <label>JK_KycDetail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_KycDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentNumber__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentNumber__c</fullName>
    <label>Kyc_documentNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentType__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentType__c</fullName>
    <label>Kyc_documentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account (ICICI)</fullName>
            </value>
            <value>
                <fullName>Aadhar Card</fullName>
            </value>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>Voter Card</fullName>
            </value>
            <value>
                <fullName>ESIC Card</fullName>
            </value>
            <value>
                <fullName>Ration Card</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>UAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_expDate__c.field-meta.xml
<CustomField>
    <fullName>Kyc_expDate__c</fullName>
    <label>Kyc_expDate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_ifscCode__c.field-meta.xml
<CustomField>
    <fullName>Kyc_ifscCode__c</fullName>
    <label>Kyc_ifscCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_nameOnDocument__c.field-meta.xml
<CustomField>
    <fullName>Kyc_nameOnDocument__c</fullName>
    <label>Kyc_nameOnDocument</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_remarks__c.field-meta.xml
<CustomField>
    <fullName>Kyc_remarks__c</fullName>
    <label>Kyc_remarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/KycToEmp__c.field-meta.xml
<CustomField>
    <fullName>KycToEmp__c</fullName>
    <label>KycToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_KycDetails</relationshipLabel>
    <relationshipName>KycToEmp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EO_BackupDMLClass.cls
public class EO_BackupDMLClass {
    private static DML uniqueInstance;

    public static DML getInstance()
    {
        if(uniqueInstance == null)
        {
            uniqueInstance = new DML();
        }
        return uniqueInstance;
    }
    public JK_KycDetail__c saveKyc(Id empId,String document,String nameondoc, String docnumber, String remarks,Id id,String expDate , String ifscCode){
        
        System.debug(Id);
        try{
            JK_KycDetail__c emp = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id = :id AND KycToEmp__c= :empId];
            emp.Kyc_documentType__c=document;
            emp.Kyc_nameOnDocument__c=nameondoc;
            emp.Kyc_documentNumber__c=docnumber;    
            emp.Kyc_remarks__c=remarks;
            emp.Kyc_expDate__c = expDate;
            emp.Kyc_ifscCode__c = ifscCode;
            if(expDate == null)
            {
                emp.Kyc_expDate__c = '';
            }
            if(ifscCode == null)
            {
                emp.Kyc_ifscCode__c = '';
            }   
            update emp;
            return emp;
        }
        catch(Exception e){
            JK_KycDetail__c emp = new JK_KycDetail__c(KycToEmp__c= empId);
            emp.Kyc_documentType__c=document;
            emp.Kyc_nameOnDocument__c=nameondoc;
            emp.Kyc_documentNumber__c=docnumber;
            emp.Kyc_remarks__c=remarks;
            emp.Kyc_expDate__c = expDate;
            emp.Kyc_ifscCode__c = ifscCode;
            if(expDate == null)
            {
                emp.Kyc_expDate__c = '';
            }
            if(ifscCode == null)
            {
                emp.Kyc_ifscCode__c = '';
            }   
            upsert emp;
           	return emp;
        }
    }
    public List<JK_KycDetail__c> fetchKyc(Id empId){

        List<JK_KycDetail__c> details = [SELECT Id,Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE KycToEmp__c = :empId ];
        System.debug(details);
        return details;
    }

    public String deleteKyc(Id id){

        JK_KycDetail__c rec = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id=:id];
        DELETE rec;
        return 'Success';
    }
    
    public JK_Employee__c saveEmployee(String firstName, String midName, String lastName,
                                              String dob, String maritalStatus, String gender,
                                              String bloodGroup, String nationality, String email,
                                              String telephone, String mobile,String tShirt,
                                              String resAddress, String resCity, String resState,
                                              String resCode, String foodPref,String lang1,Boolean lang1Read,
                                              Boolean lang1Write,Boolean lang1Speak, String lang2,
                                              Boolean lang2Read, Boolean lang2Write, Boolean lang2Speak,
                                              String lang3, Boolean lang3Read, Boolean lang3Write,
                                              Boolean lang3Speak, Id employeeId){

            JK_Employee__c emp = [SELECT Emp_firstName__c,Emp_midName__c,Emp_lastName__c,Emp_dateOfBirth__c,Emp_maritalStatus__c,
                                 Emp_gender__c,Emp_bloodGroup__c,Emp_nationality__c,Emp_emailId__c,Emp_telephone__c,Emp_mobilePhone__c,
                                 Emp_tShirtSize__c,Emp_resAddress__c,Emp_resCity__c,Emp_resState__c,Emp_resZipCode__c,
                                 Emp_foodPref__c,Emp_lang1__c,Emp_lang1Read__c,Emp_lang1Write__c,Emp_lang1Speak__c,
                                 Emp_lang2__c,Emp_lang2Read__c,Emp_lang2Write__c,Emp_lang2Speak__c,Emp_lang3__c,Emp_lang3Read__c,
                                 Emp_lang3Write__c,Emp_lang3Speak__c FROM JK_Employee__c WHERE Id = :employeeId];
            emp.Emp_firstName__c=firstName;
            emp.Emp_midName__c=midName;
            emp.Emp_lastName__c=lastName;
            emp.Emp_dateOfBirth__c=dob;
            emp.Emp_maritalStatus__c=maritalStatus;
            emp.Emp_gender__c=gender;
            emp.Emp_bloodGroup__c=bloodGroup;
            emp.Emp_nationality__c=nationality;
            emp.Emp_emailId__c=email;
            emp.Emp_telephone__c=telephone;
            emp.Emp_mobilePhone__c=mobile;
            emp.Emp_tShirtSize__c=tShirt;
            emp.Emp_resAddress__c=resAddress;
            emp.Emp_resCity__c=resCity;
            emp.Emp_resState__c=resState;
            emp.Emp_resZipCode__c=resCode;
            emp.Emp_foodPref__c=foodPref;
            emp.Emp_lang1__c=lang1;
            emp.Emp_lang1Read__c=lang1Read;
            emp.Emp_lang1Write__c=lang1Write;
            emp.Emp_lang1Speak__c=lang1Speak;
            emp.Emp_lang2__c=lang2;
            emp.Emp_lang2Read__c=lang2Read;
            emp.Emp_lang2Write__c=lang2Write;
            emp.Emp_lang2Speak__c=lang2Speak;
            emp.Emp_lang3__c=lang3;
            emp.Emp_lang3Read__c=lang3Read;
            emp.Emp_lang3Write__c=lang3Write;
            emp.Emp_lang3Speak__c=lang3Speak;
            upsert emp;
            return emp;
    
        }
    
    public JK_Employee__c fetchEmployee(Id employeeId)
    {
        try{
        JK_Employee__c emp = [SELECT Emp_firstName__c,Emp_midName__c,Emp_lastName__c,Emp_dateOfBirth__c,Emp_maritalStatus__c,
                                 Emp_gender__c,Emp_bloodGroup__c,Emp_nationality__c,Emp_emailId__c,Emp_telephone__c,Emp_mobilePhone__c,
                                 Emp_tShirtSize__c,Emp_resAddress__c,Emp_resCity__c,Emp_resState__c,Emp_resZipCode__c,
                                 Emp_foodPref__c,Emp_lang1__c,Emp_lang1Read__c,Emp_lang1Write__c,Emp_lang1Speak__c,
                                 Emp_lang2__c,Emp_lang2Read__c,Emp_lang2Write__c,Emp_lang2Speak__c,Emp_lang3__c,Emp_lang3Read__c,
                                 Emp_lang3Write__c,Emp_lang3Speak__c,Emp_commonAddressCheck__c,Emp_commAddress__c,
                                 Emp_commCity__c,Emp_commState__c,Emp_commZipcode__c FROM JK_Employee__c WHERE Id = :employeeId];
        return emp;
        }
        catch(Exception e){
            return null;
        }
    }
    public JK_Employee__c saveCommAddress(Boolean commonAddressCheck, String commAddress, String commCity,
                                             String commState, String commZipcode, Id employeeId)
    {
        JK_Employee__c emp=[SELECT Emp_commonAddressCheck__c, Emp_commAddress__c, Emp_commCity__c,
                            Emp_commState__c,Emp_commZipcode__c FROM JK_Employee__c WHERE Id = :employeeId];
        emp.Emp_commonAddressCheck__c=commonAddressCheck;
        emp.Emp_commAddress__c=commAddress;
        emp.Emp_commCity__c=commCity;
        emp.Emp_commState__c=commState;
        emp.Emp_commZipcode__c=commZipcode;
        upsert emp;
        return emp;
    }

    public List<JK_FamilyInfo__c> fetchFamilyInfo(String empId)
    {
        List<JK_FamilyInfo__c> records = [select Id,Fi_firstName__c , Fi_middleName__c , Fi_lastName__c , Fi_relation__c , Fi_dob__c  from JK_FamilyInfo__c where EmpToFi__c=:empId];
        return records;
    }
    public void deleteFamilyInfo(String empId , String  recordId)
    {
        JK_FamilyInfo__c record = [select Id from JK_FamilyInfo__c where Id=:recordId AND EmpToFi__c=:empId];
        delete record;
    }

    public  JK_FamilyInfo__c saveUpdateFamilyInfo(String relation , String fname , String mname , String lname , String dob, String rId,String empId)
    {
        if(rId == 'new')
		{
			System.debug('insert called family');
			Jk_FamilyInfo__c newRecord = new Jk_FamilyInfo__c(EmpToFi__c =empId);
			newRecord.Fi_relation__c = relation;
			newRecord.Fi_firstName__c = fname;
			newRecord.Fi_middleName__c = mname;
			newRecord.Fi_lastName__c = lname;
			newRecord.Fi_dob__c = dob;
			insert newRecord;
			return newRecord;
		}
		else {
			List<JK_FamilyInfo__c> record = [select Id , Fi_firstName__c , Fi_middleName__c , Fi_lastName__c , Fi_relation__c , Fi_dob__c from JK_FamilyInfo__c where EmpToFi__c=:empId AND Id=:rId];
			Jk_FamilyInfo__c existingRecord = record[0];
			existingRecord.Fi_relation__c = relation;
			existingRecord.Fi_firstName__c = fname;
			existingRecord.Fi_middleName__c = mname;
			existingRecord.Fi_lastName__c = lname;
			existingRecord.Fi_dob__c = dob;
			update existingRecord;
			System.debug('update called family');
			return existingRecord;
		}
    }

    public List<JK_EducationalQualification__c> fetchEducationalQualificationData(Id employeeId){
        System.debug(employeeId);
        List<JK_EducationalQualification__c> eduDetails=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId];
        System.debug(eduDetails);
        return eduDetails;
   }

   //EDUCATION
   public JK_EducationalQualification__c saveOrUpdateEducationalDetail(Id employeeId,String educationalLevel,String degree,String boardOrUniversity,String schoolOrCollegeName,String yearOfPassing,String percentageMarks,String branch, String specialisation, String postGradDegree, String marksType, Id recordId){
    System.debug(employeeId+'Id'+educationalLevel+'Level'+degree+'Degree'+boardOrUniversity+'board/university'+schoolOrCollegeName+'school name'+yearOfPassing+'year of passing'+percentageMarks+'percentage'+recordId+'record Id');
    System.debug(recordId);
    List<JK_EducationalQualification__c> detailList=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c,EQ_branchTwelth__c,EQ_postGradDegree__c,EQ_specialisation__c,EQ_marksType__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId AND Id=:recordId];
    if(detailList.size()!=0)
    {
        detailList[0].EQ_educationalLevel__c=educationalLevel;
        detailList[0].EQ_degree__c=degree;
        detailList[0].EQ_boardOrUniversity__c=boardOrUniversity;
        detailList[0].EQ_schoolOrCollegeName__c=boardOrUniversity;
        detailList[0].EQ_percentageMarks__c=percentageMarks;
        detailList[0].EQ_yearOfPassing__c=yearOfPassing;
        detailList[0].EQ_branchTwelth__c=branch;
        detailList[0].EQ_marksType__c=marksType;
        detailList[0].EQ_postGradDegree__c=postGradDegree;
        detailList[0].EQ_specialisation__c=specialisation;
        System.debug('Data:'+detailList[0]);
        update detailList[0];
        return detailList[0];    
    } else {
        System.debug('Inside exception');
        JK_EducationalQualification__c eduQualificationData= new JK_EducationalQualification__c(EqToEmp__c=employeeId);
        eduQualificationData.EQ_educationalLevel__c=educationalLevel;
        eduQualificationData.EQ_degree__c=degree;
        eduQualificationData.EQ_boardOrUniversity__c=boardOrUniversity;
        eduQualificationData.EQ_schoolOrCollegeName__c=boardOrUniversity;
        eduQualificationData.EQ_percentageMarks__c=percentageMarks;
        eduQualificationData.EQ_yearOfPassing__c=yearOfPassing;
        eduQualificationData.EQ_branchTwelth__c=branch;
        eduQualificationData.EQ_marksType__c=marksType;
        eduQualificationData.EQ_postGradDegree__c=postGradDegree;
        eduQualificationData.EQ_specialisation__c=specialisation;
        System.debug('Data:'+eduQualificationData);
        System.debug('Id: '+eduQualificationData.Name);
        upsert eduQualificationData;
        return eduQualificationData;
    }
}

public String deleteEducationalDetail(Id recordID){
    System.debug('Record Id:'+recordID);
       
     List<JK_EducationalQualification__c> educationDetailToBeDeleted=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where Id=:recordID];
     if(educationDetailToBeDeleted.size()==0){
        System.debug('No rows found'+recordID);
        return 'Error';
     }
     delete educationDetailToBeDeleted;
     return 'Successfully Deleted';
 
 }

    //WORKEXP DML
    public JK_WorkExperience__c saveUpdateData (String recordID, 
                                                       String employeeID, 
                                                       String organisationName, 
                                                       String designation, 
                                                       String startDate, 
                                                       String endDate, 
                                                       String reason){
        if(recordID == 'new'){
            JK_WorkExperience__c  newWorkExp = new JK_WorkExperience__c (WeToEmp__c = employeeID);
            newWorkExp .WE_organizationName__c = organisationName;
            newWorkExp .WE_designationWhenLeaving__c = designation;
            newWorkExp .WE_from__c = startDate;
            newWorkExp .WE_to__c = endDate;
            newWorkExp .WE_reasonForLeaving__c = reason;
            insert newWorkExp;
            return newWorkExp;
        }
        else{
            List<JK_WorkExperience__c> updateWorkExp = [SELECT Id, WE_organizationName__c, WE_designationWhenLeaving__c, 
                       WE_from__c, WE_to__c, WE_reasonForLeaving__c, WeToEmp__c 
                       FROM JK_WorkExperience__c 
                       WHERE WeToEmp__c =: employeeID AND Id =: recordID];
            JK_WorkExperience__c workExp = updateWorkExp[0];
                workExp.WE_organizationName__c = organisationName;
                workExp.WE_designationWhenLeaving__c = designation;
                workExp.WE_from__c = startDate;
                workExp.WE_to__c = endDate;
                workExp.WE_reasonForLeaving__c = reason;
                update workExp;   
                return workExp;
        }
    }

    public List<JK_WorkExperience__c> fecthWorkExp(String employeeID){
        List<JK_WorkExperience__c> refreshedWorkExp = [SELECT Id, WE_organizationName__c, WE_designationWhenLeaving__c, 
                                        WE_from__c, WE_to__c, WE_reasonForLeaving__c, WeToEmp__c 
                                        FROM JK_WorkExperience__c 
                                        WHERE WeToEmp__c =: employeeID];
        return refreshedWorkExp;
    }

    
    public void deleteWorkExp(String recordId, String employeeID){
        JK_WorkExperience__c deletedWorkExp = [SELECT Id
                                                FROM JK_WorkExperience__c 
                                                WHERE WeToEmp__c =: employeeID AND Id =: recordID];
        delete deletedWorkExp;
    }
}