force-app/main/default/objects/JK_EducationalQualification__c/JK_EducationalQualification__c.object-meta.xml
<CustomObject>
    <label>JK_EducationalQualification</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_EducationalQualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_boardOrUniversity__c.field-meta.xml
<CustomField>
    <fullName>EQ_boardOrUniversity__c</fullName>
    <label>EQ_boardOrUniversity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_degree__c.field-meta.xml
<CustomField>
    <fullName>EQ_degree__c</fullName>
    <label>EQ_degree</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_educationalLevel__c.field-meta.xml
<CustomField>
    <fullName>EQ_educationalLevel__c</fullName>
    <label>EQ_educationalLevel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Post-Graduation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_percentageMarks__c.field-meta.xml
<CustomField>
    <fullName>EQ_percentageMarks__c</fullName>
    <label>EQ_percentageMarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_schoolOrCollegeName__c.field-meta.xml
<CustomField>
    <fullName>EQ_schoolOrCollegeName__c</fullName>
    <label>EQ_schoolOrCollegeName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_yearOfPassing__c.field-meta.xml
<CustomField>
    <fullName>EQ_yearOfPassing__c</fullName>
    <label>EQ_yearOfPassing</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EqToEmp__c.field-meta.xml
<CustomField>
    <fullName>EqToEmp__c</fullName>
    <description>Educational Qualification to Employee relationship</description>
    <label>EQ_EqToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_EducationalQualifications</relationshipLabel>
    <relationshipName>JK_EducationalQualifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/JK_Employee__c.object-meta.xml
<CustomObject>
    <description>Contains basic info about the employee</description>
    <label>JK_Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_bloodGroup__c.field-meta.xml
<CustomField>
    <fullName>Emp_bloodGroup__c</fullName>
    <label>Emp_bloodGroup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A+ve</fullName>
            </value>
            <value>
                <fullName>A-ve</fullName>
            </value>
            <value>
                <fullName>B+ve</fullName>
            </value>
            <value>
                <fullName>B-ve</fullName>
            </value>
            <value>
                <fullName>AB+ve</fullName>
            </value>
            <value>
                <fullName>AB-ve</fullName>
            </value>
            <value>
                <fullName>O+ve</fullName>
            </value>
            <value>
                <fullName>O-ve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_dateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>Emp_dateOfBirth__c</fullName>
    <label>Emp_dateOfBirth</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_emailId__c.field-meta.xml
<CustomField>
    <fullName>Emp_emailId__c</fullName>
    <label>Emp_emailId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_firstName__c.field-meta.xml
<CustomField>
    <fullName>Emp_firstName__c</fullName>
    <label>Emp_firstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_foodPref__c.field-meta.xml
<CustomField>
    <fullName>Emp_foodPref__c</fullName>
    <label>Emp_foodPref</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_gender__c.field-meta.xml
<CustomField>
    <fullName>Emp_gender__c</fullName>
    <label>Emp_gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_lastName__c.field-meta.xml
<CustomField>
    <fullName>Emp_lastName__c</fullName>
    <label>Emp_lastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_maritalStatus__c.field-meta.xml
<CustomField>
    <fullName>Emp_maritalStatus__c</fullName>
    <label>Emp_maritalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Unmarried</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_midName__c.field-meta.xml
<CustomField>
    <fullName>Emp_midName__c</fullName>
    <label>Emp_midName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_mobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Emp_mobilePhone__c</fullName>
    <label>Emp_mobilePhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_nationality__c.field-meta.xml
<CustomField>
    <fullName>Emp_nationality__c</fullName>
    <label>Emp_nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>AMERICIAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resAddress__c.field-meta.xml
<CustomField>
    <fullName>Emp_resAddress__c</fullName>
    <label>Emp_resAddress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resCity__c.field-meta.xml
<CustomField>
    <fullName>Emp_resCity__c</fullName>
    <label>Emp_resCity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_Employee__c/fields/Emp_resState__c.field-meta.xml
<CustomField>
    <fullName>Emp_resState__c</fullName>
    <label>Emp_resState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_resZipCode__c.field-meta.xml
<CustomField>
    <fullName>Emp_resZipCode__c</fullName>
    <label>Emp_resZipCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_telephone__c.field-meta.xml
<CustomField>
    <fullName>Emp_telephone__c</fullName>
    <label>Emp_telephone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_Employee__c/fields/Emp_tShirtSize__c.field-meta.xml
<CustomField>
    <fullName>Emp_tShirtSize__c</fullName>
    <label>Emp_tShirtSize</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/JK_FamilyInfo__c.object-meta.xml
<CustomObject>
    <label>JK_FamilyInfo</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>JK_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_Familys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/EmpToFi__c.field-meta.xml
<CustomField>
    <fullName>EmpToFi__c</fullName>
    <label>EmpToFi</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_Familys</relationshipLabel>
    <relationshipName>JK_Familys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_dob__c.field-meta.xml
<CustomField>
    <fullName>Fi_dob__c</fullName>
    <label>Fi_dob</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_firstName__c.field-meta.xml
<CustomField>
    <fullName>Fi_firstName__c</fullName>
    <label>Fi_firstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_lastName__c.field-meta.xml
<CustomField>
    <fullName>Fi_lastName__c</fullName>
    <label>Fi_lastName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_middleName__c.field-meta.xml
<CustomField>
    <fullName>Fi_middleName__c</fullName>
    <label>Fi_middleName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_FamilyInfo__c/fields/Fi_relation__c.field-meta.xml
<CustomField>
    <fullName>Fi_relation__c</fullName>
    <label>Fi_relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/JK_KycDetail__c.object-meta.xml
<CustomObject>
    <description>Contains the KYC Details of employees.</description>
    <label>JK_KycDetail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_KycDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentNumber__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentNumber__c</fullName>
    <label>Kyc_documentNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentType__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentType__c</fullName>
    <label>Kyc_documentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account (ICICI)</fullName>
            </value>
            <value>
                <fullName>Aadhar Card</fullName>
            </value>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>Voter Card</fullName>
            </value>
            <value>
                <fullName>ESIC Card</fullName>
            </value>
            <value>
                <fullName>Ration Card</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>UAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_nameOnDocument__c.field-meta.xml
<CustomField>
    <fullName>Kyc_nameOnDocument__c</fullName>
    <label>Kyc_nameOnDocument</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_remarks__c.field-meta.xml
<CustomField>
    <fullName>Kyc_remarks__c</fullName>
    <label>Kyc_remarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/KycToEmp__c.field-meta.xml
<CustomField>
    <fullName>KycToEmp__c</fullName>
    <label>KycToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_KycDetails</relationshipLabel>
    <relationshipName>KycToEmp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EO_EDML.cls
public with sharing class EO_EDML{

    private static EO_EDML uniqueInstance;

    public static EO_EDML getInstance()
    {
        if(uniqueInstance == null)
        {
            uniqueInstance = new EO_EDML();
        }
        return uniqueInstance;
    }
//     public JK_KycDetail__c saveKyc (Id empId,String document,String nameondoc, String docnumber, String remarks,Id id){
        
//         System.debug(Id);
//         try{
//             JK_KycDetail__c emp = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id = :id AND KycToEmp__c= :empId];
//             emp.Kyc_documentType__c=document;
//             emp.Kyc_nameOnDocument__c=nameondoc;
//             emp.Kyc_documentNumber__c=docnumber;    
//             emp.Kyc_remarks__c=remarks;
//             update emp;
//             return emp;
//         }
//         catch(Exception e){
//             JK_KycDetail__c emp = new JK_KycDetail__c(KycToEmp__c= empId);
//             emp.Kyc_documentType__c=document;
//             emp.Kyc_nameOnDocument__c=nameondoc;
//             emp.Kyc_documentNumber__c=docnumber;
//             emp.Kyc_remarks__c=remarks;
//             upsert emp;
//             return emp;
//         }
//     }
//     public List<JK_KycDetail__c> fetchKyc(Id empId){

//         List<JK_KycDetail__c> details = [SELECT Id,Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE KycToEmp__c = :empId ];
//         System.debug(details);
//         return details;
//     }

//     public String deleteKyc(Id id){

//         JK_KycDetail__c rec = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id=:id];
//         DELETE rec;
//         return 'Success';
//     }
    
//     public JK_Employee__c saveEmployee(String firstName, String midName, String lastName,
//                                               String dob, String maritalStatus, String gender,
//                                               String bloodGroup, String nationality, String email,
//                                               String telephone, String mobile,String tShirt,
//                                               String resAddress, String resCity, String resState,
//                                               String resCode, String foodPref, Id employeeId){

//             JK_Employee__c emp = [SELECT Emp_firstName__c,Emp_midName__c,Emp_lastName__c,Emp_dateOfBirth__c,Emp_maritalStatus__c,
//                                  Emp_gender__c,Emp_bloodGroup__c,Emp_nationality__c,Emp_emailId__c,Emp_telephone__c,Emp_mobilePhone__c,
//                                  Emp_tShirtSize__c,Emp_resAddress__c,Emp_resCity__c,Emp_resState__c,Emp_resZipCode__c,
//                                  Emp_foodPref__c FROM JK_Employee__c WHERE Id = :employeeId];
//             emp.Emp_firstName__c=firstName;
//             emp.Emp_midName__c=midName;
//             emp.Emp_lastName__c=lastName;
//             emp.Emp_dateOfBirth__c=dob;
//             emp.Emp_maritalStatus__c=maritalStatus;
//             emp.Emp_gender__c=gender;
//             emp.Emp_bloodGroup__c=bloodGroup;
//             emp.Emp_nationality__c=nationality;
//             emp.Emp_emailId__c=email;
//             emp.Emp_telephone__c=telephone;
//             emp.Emp_mobilePhone__c=mobile;
//             emp.Emp_tShirtSize__c=tShirt;
//             emp.Emp_resAddress__c=resAddress;
//             emp.Emp_resCity__c=resCity;
//             emp.Emp_resState__c=resState;
//             emp.Emp_resZipCode__c=resCode;
//             emp.Emp_foodPref__c=foodPref;
//             upsert emp;
//             return emp;
    
//         }
    
//     public JK_Employee__c fetchEmployee(Id employeeId)
//     {
//         JK_Employee__c emp = [SELECT Emp_firstName__c,Emp_midName__c,Emp_lastName__c,Emp_dateOfBirth__c,Emp_maritalStatus__c,
//                                  Emp_gender__c,Emp_bloodGroup__c,Emp_nationality__c,Emp_emailId__c,Emp_telephone__c,Emp_mobilePhone__c,
//                                  Emp_tShirtSize__c,Emp_resAddress__c,Emp_resCity__c,Emp_resState__c,Emp_resZipCode__c,
//                                  Emp_foodPref__c FROM JK_Employee__c WHERE Id = :employeeId];
//         return emp;
//     }
//     public List<JK_FamilyInfo__c> fetchFamilyInfo(String empId)
//     {
//         List<JK_FamilyInfo__c> records = [select Id,Fi_firstName__c , Fi_middleName__c , Fi_lastName__c , Fi_relation__c , Fi_dob__c  from JK_FamilyInfo__c where EmpToFi__c=:empId];
//         return records;
//     }
//     public void deleteFamilyInfo(String empId , String  recordId)
//     {
//         JK_FamilyInfo__c record = [select Id from JK_FamilyInfo__c where Id=:recordId AND EmpToFi__c=:empId];
//         delete record;
//     }

//     public  JK_FamilyInfo__c saveUpdateFamilyInfo(String relation , String fname , String mname , String lname , String dob, String rId,String empId)
//     {
//         if(rId == 'new')
//         {
//             System.debug('insert called family');
//             Jk_FamilyInfo__c newRecord = new Jk_FamilyInfo__c(EmpToFi__c =empId);
//             newRecord.Fi_relation__c = relation;
//             newRecord.Fi_firstName__c = fname;
//             newRecord.Fi_middleName__c = mname;
//             newRecord.Fi_lastName__c = lname;
//             newRecord.Fi_dob__c = dob;
//             insert newRecord;
//             return newRecord;
//         }
//         else {
//             List<JK_FamilyInfo__c> record = [select Id , Fi_firstName__c , Fi_middleName__c , Fi_lastName__c , Fi_relation__c , Fi_dob__c from JK_FamilyInfo__c where EmpToFi__c=:empId AND Id=:rId];
//             Jk_FamilyInfo__c existingRecord = record[0];
//             existingRecord.Fi_relation__c = relation;
//             existingRecord.Fi_firstName__c = fname;
//             existingRecord.Fi_middleName__c = mname;
//             existingRecord.Fi_lastName__c = lname;
//             existingRecord.Fi_dob__c = dob;
//             update existingRecord;
//             System.debug('update called family');
//             return existingRecord;
//         }
//     }
    public List<JK_EducationalQualification__c> fetchEducationalQualificationData(Id employeeId){
        
          
        System.debug(employeeId);
        List<JK_EducationalQualification__c> eduDetails=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId];
        System.debug(eduDetails);
       return eduDetails;
   }

   public JK_EducationalQualification__c saveOrUpdateEducationalDetail(Id employeeId,String educationalLevel,String degree,String boardOrUniversity,String schoolOrCollegeName,String yearOfPassing,String percentageMarks, Id recordId){

    System.debug(employeeId+'Id'+educationalLevel+'Level'+degree+'Degree'+boardOrUniversity+'board/university'+schoolOrCollegeName+'school name'+yearOfPassing+'year of passing'+percentageMarks+'percentage'+recordId+'record Id');
   // JK_EducationalQualification__c detail=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId AND Id=:recordId];
    System.debug(recordId);
    List<JK_EducationalQualification__c> detailList=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId AND Id=:recordId];
    if(detailList.size()!=0)
    {

        detailList[0].EQ_educationalLevel__c=educationalLevel;
        detailList[0].EQ_degree__c=degree;
        detailList[0].EQ_boardOrUniversity__c=boardOrUniversity;
        detailList[0].EQ_schoolOrCollegeName__c=boardOrUniversity;
        detailList[0].EQ_percentageMarks__c=percentageMarks;
        detailList[0].EQ_yearOfPassing__c=yearOfPassing;
        System.debug('Data:'+detailList[0]);
        //System.debug('Id: '+detail.Name);
        update detailList[0];
        return detailList[0];
        
    } else {
        System.debug('Inside exception');
        JK_EducationalQualification__c eduQualificationData= new JK_EducationalQualification__c(EqToEmp__c=employeeId);
        eduQualificationData.EQ_educationalLevel__c=educationalLevel;
        eduQualificationData.EQ_degree__c=degree;
        eduQualificationData.EQ_boardOrUniversity__c=boardOrUniversity;
        eduQualificationData.EQ_schoolOrCollegeName__c=boardOrUniversity;
        eduQualificationData.EQ_percentageMarks__c=percentageMarks;
        eduQualificationData.EQ_yearOfPassing__c=yearOfPassing;
        System.debug('Data:'+eduQualificationData);
        System.debug('Id: '+eduQualificationData.Name);
        upsert eduQualificationData;
        return eduQualificationData;
    }

}
public String deleteEducationalDetail(Id recordID){

    // JK_KycDetail__c recordToBeDeleted = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id=:id];
    System.debug('Record Id:'+recordID);
       
     List<JK_EducationalQualification__c> educationDetailToBeDeleted=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where Id=:recordID];
     if(educationDetailToBeDeleted.size()==0){
        System.debug('No rows found'+recordID);
        return 'Error';
     }
     delete educationDetailToBeDeleted;
     return 'Successfully Deleted';
 
 } 

}