force-app/main/default/objects/JK_EducationalQualification__c/JK_EducationalQualification__c.object-meta.xml
<CustomObject>
    <label>JK_EducationalQualification</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_EducationalQualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_boardOrUniversity__c.field-meta.xml
<CustomField>
    <fullName>EQ_boardOrUniversity__c</fullName>
    <label>EQ_boardOrUniversity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_degree__c.field-meta.xml
<CustomField>
    <fullName>EQ_degree__c</fullName>
    <label>EQ_degree</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_educationalLevel__c.field-meta.xml
<CustomField>
    <fullName>EQ_educationalLevel__c</fullName>
    <label>EQ_educationalLevel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Post-Graduation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_percentageMarks__c.field-meta.xml
<CustomField>
    <fullName>EQ_percentageMarks__c</fullName>
    <label>EQ_percentageMarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_schoolOrCollegeName__c.field-meta.xml
<CustomField>
    <fullName>EQ_schoolOrCollegeName__c</fullName>
    <label>EQ_schoolOrCollegeName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_EducationalQualification__c/fields/EQ_yearOfPassing__c.field-meta.xml
<CustomField>
    <fullName>EQ_yearOfPassing__c</fullName>
    <label>EQ_yearOfPassing</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_EducationalQualification__c/fields/EqToEmp__c.field-meta.xml
<CustomField>
    <fullName>EqToEmp__c</fullName>
    <description>Educational Qualification to Employee relationship</description>
    <label>EQ_EqToEmp</label>
    <referenceTo>JK_Employee__c</referenceTo>
    <relationshipLabel>JK_EducationalQualifications</relationshipLabel>
    <relationshipName>JK_EducationalQualifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/JK_KycDetail__c.object-meta.xml
<CustomObject>
    <description>Contains the KYC Details of employees.</description>
    <label>JK_KycDetail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JK_KycDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentNumber__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentNumber__c</fullName>
    <label>Kyc_documentNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_documentType__c.field-meta.xml
<CustomField>
    <fullName>Kyc_documentType__c</fullName>
    <label>Kyc_documentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account (ICICI)</fullName>
            </value>
            <value>
                <fullName>Aadhar Card</fullName>
            </value>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>Voter Card</fullName>
            </value>
            <value>
                <fullName>ESIC Card</fullName>
            </value>
            <value>
                <fullName>Ration Card</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>UAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingApp/force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_nameOnDocument__c.field-meta.xml
<CustomField>
    <fullName>Kyc_nameOnDocument__c</fullName>
    <label>Kyc_nameOnDocument</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JK_KycDetail__c/fields/Kyc_remarks__c.field-meta.xml
<CustomField>
    <fullName>Kyc_remarks__c</fullName>
    <label>Kyc_remarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EO_EmpEducationalQualificationController.cls
public class EO_EmpEducationalQualificationController {
    @RemoteAction
   public static List<JK_EducationalQualification__c> fetchEducationalQualificationData(Id employeeId){
        System.debug(employeeId);
        List<JK_EducationalQualification__c> eduDetails=EO_EDML.getInstance().fetchEducationalQualificationData(employeeId);
        System.debug(eduDetails);
       return eduDetails;
   }
    
    @RemoteAction
    public static JK_EducationalQualification__c saveOrUpdateEducationalDetail(Id employeeId,String educationalLevel,String degree,String boardOrUniversity,String schoolOrCollegeName,String yearOfPassing,String percentageMarks, Id recordId){

        System.debug(employeeId+'Id'+educationalLevel+'Level'+degree+'Degree'+boardOrUniversity+'board/university'+schoolOrCollegeName+'school name'+yearOfPassing+'year of passing'+percentageMarks+'percentage'+recordId+'record Id');
       // JK_EducationalQualification__c detail=[select EQ_educationalLevel__c,EQ_degree__c,EQ_boardOrUniversity__c,EQ_schoolOrCollegeName__c,EQ_yearOfPassing__c,EQ_percentageMarks__c from JK_EducationalQualification__c where EqToEmp__c=:employeeId AND Id=:recordId];
        System.debug(recordId);
        JK_EducationalQualification__c detailList=EO_EDML.getInstance().saveOrUpdateEducationalDetail(employeeId,educationalLevel,degree,boardOrUniversity,schoolOrCollegeName,yearOfPassing,percentageMarks,recordId);
   return detailList;
}

@RemoteAction 
public static String deleteEducationalDetail(Id recordID){

   // JK_KycDetail__c recordToBeDeleted = [SELECT Kyc_documentType__c,Kyc_nameOnDocument__c,Kyc_documentNumber__c,Kyc_remarks__c FROM JK_KycDetail__c WHERE Id=:id];
      
    String deleteEducationalQualificationStatus= EO_EDML.getInstance().deleteEducationalDetail(recordID);

    return deleteEducationalQualificationStatus;

} 
}